function(add_tutorial_test name)
  add_executable(${name} ${name}.cpp)
  target_link_libraries(${name} PRIVATE gr-tutorial tutorial-ut gnuradio4::gnuradio-blocklib-core)
  add_test(NAME ${name} COMMAND ${name})
  set_tests_properties(${name} PROPERTIES TIMEOUT 30)
endfunction()
add_tutorial_test(qa_Gain)
add_tutorial_test(qa_Square)
add_tutorial_test(qa_Packetizer)
add_tutorial_test(qa_TagForwarder)
add_tutorial_test(qa_MovingAverage)
target_link_libraries(qa_MovingAverage PRIVATE gnuradio4::gr-testing gnuradio4::gnuradio-core gnuradio4::gnuradio-blocklib-core)
target_link_libraries(qa_TagForwarder PRIVATE gnuradio4::gr-testing gnuradio4::gnuradio-core gnuradio4::gnuradio-blocklib-core)
target_link_libraries(qa_Packetizer PRIVATE gnuradio4::gr-testing gnuradio4::gnuradio-core gnuradio4::gnuradio-blocklib-core)
add_tutorial_test(qa_TutorialAvailableBlocks)
target_link_libraries(qa_TutorialAvailableBlocks PRIVATE gnuradio4::GrTutorialBlocksShared)
