cmake_minimum_required(VERSION 3.27)
project(gnuradio4Tutorial VERSION 4.0.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)
option(ENABLE_TESTING "Build tutorial tests" ON)
option(ENABLE_EXAMPLES "Build tutorial examples" ON)
find_package(gnuradio4 CONFIG REQUIRED)
find_package(GnuRadioBlockLib CONFIG REQUIRED)
if(ENABLE_TESTING OR ENABLE_EXAMPLES)
  find_package(gnuradio4Blocks CONFIG REQUIRED)
endif()
if(ENABLE_TESTING)
  enable_testing()
  include(cmake/Dependencies.cmake)
endif()
add_subdirectory(blocks/tutorial)
set(package_dir "${CMAKE_INSTALL_LIBDIR}/cmake/gnuradio4Tutorial")
configure_package_config_file(cmake/gnuradio4TutorialConfig.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/gnuradio4TutorialConfig.cmake
  INSTALL_DESTINATION ${package_dir})
write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/gnuradio4TutorialConfigVersion.cmake
  VERSION ${PROJECT_VERSION} COMPATIBILITY SameMajorVersion)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/gnuradio4TutorialConfig.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/gnuradio4TutorialConfigVersion.cmake DESTINATION ${package_dir})
install(EXPORT gnuradio4TutorialTargets NAMESPACE gnuradio4:: DESTINATION ${package_dir})
